### ISSUE TITLE
Unable to download datasets from hub using run_overlim.sh

### ISSUE THREAD

**Issue by AddedK** [kb-labb/overlim_eval#1]
I can not run the script properly because it fails to download the dataset for all tasks from Huggingface.
For example, the error message "FileNotFoundError: Couldn't find file at https://huggingface.co/datasets/KBLab/overlim/resolve/main/data/sv\mnli.tar.gz" is returned when trying to do the mnli task.

It still seems possible to download the tar files manually from for example https://huggingface.co/datasets/KBLab/overlim/tree/main/data/sv. I will default to doing this until the issue is resolved, although it is more cumbersome.

**Comment by RobinQrtz** [comment]
Hi,
I can unfortunately not recreate the error.
I can suggest you remove you huggingface-datasets cache and try just downloading the dataset in an interactive python session

To completely remove all cached huggingface-datasets (or wherever you store them, if not in the home directory)
```
rm -rf ~/.cache/huggingface/datasets
```

Open an interactive python session and run

```
from datasets import load_dataset
dataset = load_dataset("KBLab/overlim", "mnli_sv")
```

**Comment by AddedK** [comment]
Hi,

Clearing the cache and running the commands does not seem to work on my Windows 10 Desktop. I receive the same error message when trying to load the mni_sv dataset. However, when running the commands on my Ubuntu Thinkpad, it works perfectly fine.

Since the issue seems localized to on one of my computers, I will close this issue as it doesn´t seem to be on your end. I might return and document how I solved the issue for my desktop, if I manage to do it.
